/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuestRouteImport } from './routes/quest'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVoiceChatRouteImport } from './routes/api/voice-chat'
import { Route as ApiGenerateTurnRouteImport } from './routes/api/generate-turn'

const QuestRoute = QuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceChatRoute = ApiVoiceChatRouteImport.update({
  id: '/api/voice-chat',
  path: '/api/voice-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateTurnRoute = ApiGenerateTurnRouteImport.update({
  id: '/api/generate-turn',
  path: '/api/generate-turn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/quest': typeof QuestRoute
  '/api/generate-turn': typeof ApiGenerateTurnRoute
  '/api/voice-chat': typeof ApiVoiceChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/quest': typeof QuestRoute
  '/api/generate-turn': typeof ApiGenerateTurnRoute
  '/api/voice-chat': typeof ApiVoiceChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/quest': typeof QuestRoute
  '/api/generate-turn': typeof ApiGenerateTurnRoute
  '/api/voice-chat': typeof ApiVoiceChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/map' | '/quest' | '/api/generate-turn' | '/api/voice-chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map' | '/quest' | '/api/generate-turn' | '/api/voice-chat'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/quest'
    | '/api/generate-turn'
    | '/api/voice-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  QuestRoute: typeof QuestRoute
  ApiGenerateTurnRoute: typeof ApiGenerateTurnRoute
  ApiVoiceChatRoute: typeof ApiVoiceChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quest': {
      id: '/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof QuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice-chat': {
      id: '/api/voice-chat'
      path: '/api/voice-chat'
      fullPath: '/api/voice-chat'
      preLoaderRoute: typeof ApiVoiceChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-turn': {
      id: '/api/generate-turn'
      path: '/api/generate-turn'
      fullPath: '/api/generate-turn'
      preLoaderRoute: typeof ApiGenerateTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  QuestRoute: QuestRoute,
  ApiGenerateTurnRoute: ApiGenerateTurnRoute,
  ApiVoiceChatRoute: ApiVoiceChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
